### ISSUE TITLE
Agency name will be cropped if it is > 2 lines long

### ISSUE THREAD

**Issue by anselmbradford** [opentraildata/OpenTrails-Mobile#100]
The agency name on the notifications view will be cropped if it's greater than 2 lines long. The `text-overflow` CSS property is an option to add an ellipsis in this situation, but it requires the text be all on one line as far as I know. So this issue is an FYI for long agency names. The height on `#notification-source` is hardcoded so the area below it can be calculated to allow for scrolling of the notice list.

**Comment by Mr0grog** [comment]
_Since you are WebKit only,_ you can use `-webkit-line-clamp` to get an ellipses for text clipped to more than one line. Only works (probably only will ever) in WebKit and Blink based browsers.

**Comment by anselmbradford** [comment]
Nice! That's perfect! http://dropshado.ws/post/1015351370/webkit-line-clamp

**Comment by anselmbradford** [comment]
That can replace what's here --> https://github.com/codeforamerica/trails-mobile/blob/master/www/css/application.css#L783

**Comment by alanjosephwilliams** [comment]
wow I totally missed this issue until right now, thanks for chiming in @Mr0grog !
