### ISSUE TITLE
Black background or lack of background on Trail-details view

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#115]
#### Description

When the trail-view is expanded, the user is then able to scroll down to read detailed information about the trail. We have implemented simple physics for this scroll interaction. It feels good. However, when the user pulls down, the scrollable container moves completely, revealing a black background. This can be confusing, and makes the app feel broken.
#### Actions

Identify the DOM architecture that causes this. If it is a DOM element with a black background, apply a #f6f6f6 background. My guess is that the issue is more nuanced than that. Update the DOM so that when the user pulls down on the content, no black area is revealed.

![2014-05-08 14 26 37](https://cloud.githubusercontent.com/assets/2983464/2921718/8a560480-d6f7-11e3-972d-3bec97777757.png)

**Comment by anselmbradford** [comment]
I can't reproduce this. It may have been fixed in https://github.com/codeforamerica/trails-mobile/pull/126. I simplified the scrolling code in that branch.

![113-details](https://cloud.githubusercontent.com/assets/704760/2942997/f5d98f0c-d9bc-11e3-84e8-39c7f866bfd1.gif)

**Comment by alanjosephwilliams** [comment]
This is resolved on my phone, and not reproducible on other devices, so I am closing for now
