### ISSUE TITLE
Navigation back from web views of Google Maps

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#117]
#### Description

When the user taps "get directions" on the trail view, or the address of the agency in the notifications-view, the app takes their current location and the address provided, and opens Google Maps in the browser. Because we are using PhoneGap, this means that the app itself is the vehicle for this webview. As a result, there is no way to navigate back to the application once sent to Google Maps. The user is forced to close  and restart the app completely.
#### Action

Either implement some means by which navigation elements of To The Trails remain when Google Maps is opened---for example, the bottom UI. Or create a simpler "close" UI element that allows the user to return to To The Trails. If neither of these is possible, we may need to consider removing the get directions features.

@anselmbradford your perspective here is welcome.

**Comment by lovehandle** [comment]
Unfortunately this fix opens the directions in Apple Maps, but I think that's actually a more expected interaction (as opposed to opening google maps in a nested web view).

We could also open Google Maps in Safari. Thoughts?

https://github.com/codeforamerica/trails-mobile/commit/4ef6353b152a6705afe9b273b48028226cfca66d

**Comment by alanjosephwilliams** [comment]
Performance will be better with a native app, and switching back and forth between apps seems like a pretty conventional pattern. Let's go with the former.
