### ISSUE TITLE
Remove Inactive Chevrons

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#118]
#### Description

Currently, we include an "inactive" chevron when there is no further item to navigate toward. With updates to the color scheme, they are no longer visually consistent with the design. Moreover, they feel like value-less visual weight on the screen. 
#### Action

Remove the chevrons, but maintain the current layout.

**Comment by anselmbradford** [comment]
Consider removing trails that have "1 of 1" + chevrons too:

![screen shot 2014-05-11 at 1 19 46 pm](https://cloud.githubusercontent.com/assets/704760/2939489/afaaf7dc-d949-11e3-9d6a-064f4cb7fd7a.png)

**Comment by alanjosephwilliams** [comment]
Good call

**Comment by anselmbradford** [comment]
"1 of 1" chevrons removed in https://github.com/codeforamerica/trails-mobile/pull/125 ... alignment might be an issue though. They're just kinda floating there not aligned with anything now.

**Comment by alanjosephwilliams** [comment]
Not sure I quite follow @anselmbradford ---- when you say "they're" are you referring to the text "1 of 1"?

**Comment by anselmbradford** [comment]
Yes, precisely, the "1 of 1" text... Just looks a little off to me. The "x" also in regard to aligning with the design.

![screen shot 2014-05-12 at 2 13 49 pm](https://cloud.githubusercontent.com/assets/704760/2950397/5b27736c-da1a-11e3-8352-79b7379a08cb.png)

Perhaps the text for "1 of 1" just needs to be larger, e.g.:

![screen shot 2014-05-12 at 2 18 20 pm](https://cloud.githubusercontent.com/assets/704760/2950490/2420a0a4-da1b-11e3-9206-7e55c4de83f2.png)

![screen shot 2014-05-12 at 2 19 05 pm](https://cloud.githubusercontent.com/assets/704760/2950489/24204e88-da1b-11e3-882e-1627d28a90f5.png)

**Comment by alanjosephwilliams** [comment]
Thanks Ans. Yes we will need to check the alignments on each of these. My
preference is to hide "1 of 1" altogether when there is no other trail at
that location.

AJW

On Mon, May 12, 2014 at 2:20 PM, Ans notifications@github.com wrote:

> Yes, precisely, the "1 of 1" text... Just looks a little off to me. The
> "x" also in regard to aligning with the design.
> 
> [image: screen shot 2014-05-12 at 2 13 49 pm]https://cloud.githubusercontent.com/assets/704760/2950397/5b27736c-da1a-11e3-8352-79b7379a08cb.png
> 
> Perhaps the text for "1 of 1" just needs to be larger, e.g.:
> 
> [image: screen shot 2014-05-12 at 2 18 20 pm]https://cloud.githubusercontent.com/assets/704760/2950490/2420a0a4-da1b-11e3-9206-7e55c4de83f2.png
> 
> [image: screen shot 2014-05-12 at 2 19 05 pm]https://cloud.githubusercontent.com/assets/704760/2950489/24204e88-da1b-11e3-882e-1627d28a90f5.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/issues/118#issuecomment-42889889
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by anselmbradford** [comment]
Yeah agreed, hiding it altogether is the way to go.
