### ISSUE TITLE
Update Notifications View "1 of 3 Stewards" to be dynamic

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#120]
#### Description

We have some placeholder text in the navigation for the notifications view. It says "1 of 3 Stewards". Let's update it to be dynamic.
#### Actions
- Update the number of stewards to reflect the number of stewards in the data
- Let's update the first numeral to reflect which agency is currently being viewed.

**Comment by anselmbradford** [comment]
Is "Stewards" the right word here? I feel like "Agencies" is more colloquial, but maybe that's just me.

**Comment by alanjosephwilliams** [comment]
You are right---and we may want to change that. However, "stewards" is the noun used in the data model because it it includes organizations more diverse than just agencies. Thus, the same will be true for those sending messages. That said---stewards is a term of art and not considerate of user literacy on the matter.
