### ISSUE TITLE
Implement dynamic copy based on Search and Filter Terms

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#138]
We need to change the currently static "Show Trails for All Activities" to the following:
##### No filters selected

"Show Trails for All Activities"
##### Filters selected

"Show Trails for [filter, filter, filter, and filter]
"Hiking"
"Biking"
"Horse Riding"
"Cross Country Skiing"

I do not think the order in which those filter terms appears is important. I think it is equally usable whether the sentence follows an fixed order, or whether the order reflects the sequence in which each filter was activated.

![2014-05-26 17 19 53](https://cloud.githubusercontent.com/assets/2983464/3086493/0bbb97fe-e537-11e3-8da7-45f67496a1fc.png)

**Comment by anselmbradford** [comment]
Plug your device in!

**Comment by alanjosephwilliams** [comment]
haha I did I did!
