### ISSUE TITLE
Disable Search and Filter area movement

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#139]
Currently, the search and filter area in the list/search view can be moved over to the right. They should have a fixed width that fits the viewport.

![2014-05-26 18 06 12](https://cloud.githubusercontent.com/assets/2983464/3086569/235cf9d0-e53b-11e3-8d5e-ccce99888e5f.png)

**Comment by anselmbradford** [comment]
I was told about a technique to use `text-align:justify` to evenly space buttons and also be responsive across differing viewport widths.

See http://stackoverflow.com/questions/7647195/evenly-spaced-list-items

**Comment by alanjosephwilliams** [comment]
(see I told you I plugged it in)
