### ISSUE TITLE
Make Terrain Map Tiles Available offline

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#14]
- We will be designing our own custom terrain tile set
- We should provide an off-the-shelf satellite tile set as well. Users will be able to toggle between the two.
- The extent of that tile set should be defined by the extent of the trail data uploaded.
  - 5mi buffer from from farthest out feature?
- In the meantime, we can prototype using the Cleveland Metro Extract of OSM

**Comment by alanjosephwilliams** [comment]
While we can't include map tiles for download while using PhoneGap build and TestFlight, we ultimately want to make sure we have a set of terrain tiles that covers the entire extent of the trail network available. This should have significant performance benefits, and helps address the offline use case more effectively.

**Comment by lovehandle** [comment]
See #40
