### ISSUE TITLE
Design: Indicate that no messaging functionality is present

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#155]
For the v1 implementation, there will be no agency that has adopted the messaging feature. As a result, we need to:

change the default tab of the [notifications-view](https://github.com/codeforamerica/OpenTrails-Mobile/blob/master/www/index.html#L45) to "content", and gray out or otherwise indicate that "Notices" functionality is not available.

![2014-08-21_14_14_18](https://cloud.githubusercontent.com/assets/2983464/4003642/a9c77e42-2978-11e4-9831-f8808c848114.jpg)

**Comment by jmoe** [comment]
We are actually going to include messaging from OuterSpatial
