### ISSUE TITLE
Organization logo images will need to be drawn from OuterSpatial

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#156]
Pinging @jmoe

Currently, the application renders information about park agencies based on a stewards.csv file. That file does not contain logos for each steward, but the app currently displays them. I'm not sure what to recommend in terms of concrete development tasks at this point.

**Comment by alanjosephwilliams** [comment]
The lowest LOE approach would be to simply remove logo images for the time being.

**Comment by jmoe** [comment]
The logo was removed from the UI for now.
