### ISSUE TITLE
Search for matches in Description and Trailheads, in addition to Trail Name

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#21]

**Comment by alanjosephwilliams** [comment]
Currently, I believe search only matches against Trail names.

Let's expand the data that we reference search terms against. For example, if someone searches "waterfall" let's give them any results that have the word "waterfall" in the description, not just the name of the trail.

**Comment by lovehandle** [comment]
https://github.com/codeforamerica/trails-mobile/commit/7b5fbfabd75bbcd7a17290d3a774de950b3e88d2
