### ISSUE TITLE
Update position of "Search" and "Recenter" Btns in Map View

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#24]
These squares are 80px by 80px squares.

They are offset from the top of the viewport by 50px. 

They are each offset from their respective sides of the viewport by 30px.

**Comment by alanjosephwilliams** [comment]
The size feels right, but the positioning relative the viewport should be changed. I recommend bringing it toward the edges both to the side and up.

![2014-03-25 16 13 07](https://f.cloud.github.com/assets/2983464/2519512/97b23654-b473-11e3-8e16-5254d54c6652.png)

**Comment by lovehandle** [comment]
@alanjosephwilliams is this still valid? you want to take ownership of this one?

**Comment by lovehandle** [comment]
Bump. I'm going to close this one, as it seems to have died. Feel free to reopen if it's still valid.

**Comment by alanjosephwilliams** [comment]
I did this, should have closed. Thanks for spring cleaning.

On Sat, Apr 26, 2014 at 6:04 PM, Ryan Closner notifications@github.comwrote:

> Closed #24 https://github.com/codeforamerica/trails-mobile/issues/24.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/issues/24
> .

## 

t:  @alanjosephwilli
p: 817 713 6264
