### ISSUE TITLE
4s ios 7.1 incompatible with release

### ISSUE THREAD

**Issue by gwpangloss** [opentraildata/OpenTrails-Mobile#26]
Will not install ToTheTrails v 0.0.1.

Install good on iPhone 5 ios 6.1.4

**Comment by alanjosephwilliams** [comment]
Thanks @gwpangloss. Will investigate today.

**Comment by alanjosephwilliams** [comment]
@gwpangloss Interestingly enough, you are not showing up as an installed tester. I have just resent an invitation. Hopefully this well help move us toward resolution.

**Comment by gwpangloss** [comment]
I think I'm good for the invite- it worked on my iPhone 5, and I could respond to the invite on my 4s.  Just fyi, v 0.0.1 #6 also does not install on the 4s iOS 7.1.

**Comment by alanjosephwilliams** [comment]
Hey Paul---I'm going to send you an invite for a more recent release.
Hopefully that will resolve the issue--we haven't seen install problems on
4s here (yet).

AJW

On Fri, Apr 11, 2014 at 10:55 AM, Paul C. notifications@github.com wrote:

> I think I'm good for the invite- it worked on my iPhone 5, and I could
> respond to the invite on my 4s. Just fyi, v 0.0.1 #6https://github.com/rclosner/trails-mobile/issues/6also does not install on the 4s iOS 7.1.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rclosner/trails-mobile/issues/26#issuecomment-40234957
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by gwpangloss** [comment]
Cool, will keep an eye out.

**Comment by gwpangloss** [comment]
Got it.  V0.0.1 #10 worked on my 5, but in the 4s it's still listed as "incompatible" in testflight.  

![image](https://cloud.githubusercontent.com/assets/4440549/2684808/3c713c2e-c1be-11e3-8854-6e2abf86178a.png)

**Comment by alanjosephwilliams** [comment]
Roger that, thanks for the screenshot Paul. Turns out your particular 4s
had not made it into the provisioning profile. I have updated it now, so
give it another spin when you have a minute.

On Fri, Apr 11, 2014 at 2:20 PM, Paul C. notifications@github.com wrote:

> Got it. V0.0.1 #10 https://github.com/rclosner/trails-mobile/issues/10worked on my 5, but in the 4s it's still listed as "incompatible" in
> testflight.
> 
> [image: image]https://cloud.githubusercontent.com/assets/4440549/2684808/3c713c2e-c1be-11e3-8854-6e2abf86178a.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rclosner/trails-mobile/issues/26#issuecomment-40254539
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by gwpangloss** [comment]
Bingo.  Thanks!
