### ISSUE TITLE
Geolocation Error States

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#3]
- Use of Geolocation Denied
  - establish a default position on which to center the map.

It would be nice to make this location a variable that can be easily changed in future deployments.

One possible solution would be to make this the center of the map tile extent provided in each deployment of the app.

**Comment by lovehandle** [comment]
The application currently allows for a default location to be specified. We should remove the current location marker from the screen, however, when geolocation is denied. We should also be specifying these defaults into a configuration file that can be easily modified.

**Comment by lovehandle** [comment]
Closing this for now. Creating an issue for a configuration file. 

https://github.com/codeforamerica/trails-mobile/commit/ec0916ddbbb2a6744e849eb6c7f653876b763ef8
