### ISSUE TITLE
Pan and Zoom to Frame Trail Selected from Search

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#38]
Currently, we do not change the map when a trail is selected from the list / search.

Let's:
- pan to the trail's centerpoint
- zoom out to fit the full trail extent if necessary
- animate (ease?) that movement if it is jarring.

**Comment by alanjosephwilliams** [comment]
@rclosner it looks like your last commit may have addressed this. True fact?

**Comment by lovehandle** [comment]
Yes. A little wonky at times, but it does the trick.
