### ISSUE TITLE
Implement Notifcations

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#42]
- Allow a list of notifications to be downloaded.
  - At minimum, each time the app is opened?
  - We should probably have a "check for more messages" button visible when              there are no messages to display.
- Allow users to close/dismiss a notification.
- Give an indication (small blue dot) next to the info icon on the bottom UI that there are unread messages.

**Comment by alanjosephwilliams** [comment]
@rclosner I shared the notifications.json file and directory with @jmoe from Trailhead Labs. 

Leaving this open for now, as we still need to address:
- Source of notifications
- Frequency with which notifications are fetched
- UI indications of new notifications

**Comment by jmoe** [comment]
Excellent! I'll be taking a look as we finalize our designs for our messaging features.

**Comment by lovehandle** [comment]
Notifications are implemented with the exception of using localstorage to mark them as read. All we need is an API endpoint and they'll be live in the application.

**Comment by lovehandle** [comment]
Given that we've got an endpoint set up, I'm going to close this issue, and create a new one describing the process of marking notifications as read in localstorage.
