### ISSUE TITLE
Implement Activity Filters

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#43]
On the List / Search Screen, we need to implement simple checkbox filters for the trails, in addition to the existing search feature. Our partners have communicated that this feature is a must-have.
- Include row of four icons that serve as checkboxes. 
- Filter the list of trails based on which meet the checkbox criteria. 
- Give a feedback message confirming the action, and update the list. 
- Allow search of the filtered list.

Filter button will be the icons shown on the Trail Preview. They represent the following activities, each of which is an attribute of namedTrails.
- foot
- bike
- ski
- horse

**Comment by lovehandle** [comment]
https://github.com/codeforamerica/trails-mobile/commit/cacae4277756e07acca1819787345f936b8fcfc4
