### ISSUE TITLE
In bottom nav UI, update map -> list -> map icon behavior to improve navigation

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#48]
**Description**

From the default "map-view" state, when a user taps the show-search-view icon (a bulleted list) in the bottom navigation row, they are taken to the "search-view", listing all the trials and offering search and filter functionality. The show-search-view-icon is then replaced with a show-map-view icon (the tilted map).

Once a list item is tapped, the "search-view" recedes behind the "map-view" and a trial-preview that can be expanded or closed is shown.

The show-map-icon remains. Tapping it closes the trail-preview. That interaction is already afforded by the close-button in the top right of the trail-preview. 

Instead, let's swap the to-map icon for a to-search icon, and allow it essentially to serve as a "back button" to the search-view.

**Comment by lovehandle** [comment]
https://github.com/codeforamerica/trails-mobile/commit/de1a1440ca5e0d529755dd81cfbf846aa7bce16a
