### ISSUE TITLE
Amenities listed for Trailheads not yet dynamic

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#49]
Each trail is associated with a trailhead. We have unique "views" for each trail-trailhead pair.

We list attributes of the trailhead at the bottom of each trail-view. There are four properties in trailheads.geojson that we call "amenities" --- parking, drinking water, information, and restrooms. 

Currently, we display those as list items, but we are not actually checking against the data and removing them if they evaluate to false.

**Comment by lovehandle** [comment]
https://github.com/codeforamerica/trails-mobile/commit/8330b0ccf8eb51e4f750e09075d1fa8fc8388a23
