### ISSUE TITLE
When trailhead is selected, trail-view position should always be set to closed/preview

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#50]
Currently, when the user taps on a trailhead, they are shown a "preview" of the first among a group of trails accessible from that point. That preview can currently be expanded by tapping or swiping. The user can close the view altogether from either position--preview or full.

If the user closes the trail while it is in the expanded position, that position will remain when they open the next trail, obfuscating the map, and if they had scrolled down, often the Trail Name itself.

Let's change this so that when trail view is closed, the position is reverted back to "preview" or collapsed.

**Comment by lovehandle** [comment]
https://github.com/codeforamerica/trails-mobile/commit/d8b0f7ff674c60f6cbdbdedf0e797038c6a1c756

**Comment by alanjosephwilliams** [comment]
Updated worked well as described.

Turns out we need to also reset the scroll position itself. The current experience is:
- preview trail
- expand trail
- scroll down
- close trail
- preview next trail
- expand next trail
  -> scrolled-down position remains

**Comment by lovehandle** [comment]
@alanjosephwilliams Is this not resolved? It looks like you made a change that fixed this bug.

**Comment by lovehandle** [comment]
It seems to be fixed on my local copy. Closing this, but feel free to reopen if problem remains.
