### ISSUE TITLE
Animate zoom of more than three z-indexes.

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#51]
There are some very long regional trails. When user selects those trails by either tapping on trailhead or navigated through the list at a given trialhead, the map will zoom to frame the trail's full extent.

This can be very jarring for the longest trails. My understanding is that we are already using easing calculations for map pans and zooms. If those are in CSS (which some of our transformations are) they may not be easy to programmatically adjust. If it is in JS though, seems like it could be a low-cost, high-return enhancement.

**Comment by lovehandle** [comment]
We don't really have that kind of introspection into the trail bounds at the moment. You're trying to slow down the easing for only interactions where (old zoom level - new zoom level > 3)?

**Comment by alanjosephwilliams** [comment]
That is indeed what I am referring to. Let's table it for now and return next sprint.
