### ISSUE TITLE
Trail-View flashes when swiped up or down.

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#52]
Unfortunately, I think the combination of scrolling and swipe up-and-down interactions on the trail-view are the culprit.

If it is possible to investigate fixes that would allow us to keep both interactions, I think we should. The swipe-down-to-close is a much less expensive interaction than reaching for the tab to pull down from the very top of the screen. I can imagine that we may have to kill up and down swiping altogether though.

**Comment by lovehandle** [comment]
Not sure how to handle this one at the moment. For now let's remove the interaction, and we can always add it back in the future if we're able to figure out how to make it less buggy.

https://github.com/codeforamerica/trails-mobile/commit/9203eb17fdf44dd35f80ceedeb7b8fb673fe045f

**Comment by alanjosephwilliams** [comment]
Unfortunately, we are still getting it. Which means that it's probably an issue elsewhere (I am going to interpret that as good news, potentially allowing us to bring back the swipe up/down interaction. I'm going to investigate and report back.

**Comment by Mr0grog** [comment]
This is happening because the content is switching between layer-backed and non-layer-backed when it moves between fullscreen and not fullscreen (basically, the drawn bitmap for the content is getting moved back and forth between GPU and main memory, which is _really_ slow). The layer-backing is being caused by `-webkit-overflow-scrolling: touch` being used on `.trail-and-trailhead-data`.

**Comment by alanjosephwilliams** [comment]
Thanks for diagnosing Rob. 

In your cursory estimation, is it likely or not likely that there is a resolution allowing us to maintain the fullscreen+scroll /  not fullscreen interaction pattern, while avoiding the switch between layer-backed and non-layer backed?

**Comment by Mr0grog** [comment]
There's a patch with a demo of a fix here: https://github.com/codeforamerica/trails-mobile/pull/61

**Comment by alanjosephwilliams** [comment]
Unfortunately, looks like we will need to take another pass at addressing this issue.

**Comment by Mr0grog** [comment]
What's happening?

**Comment by alanjosephwilliams** [comment]
When the trail-view is expanded, swiping to scroll up or down will cause the content to flash. It _looks_ like the same problem, but presumably it is not. I'll see if i can record it.

**Comment by Mr0grog** [comment]
Hmmm, I'm not experiencing that at all on the version you just shipped (which I think includes the patch). Unless I'm misunderstanding what you're saying :\

**Comment by alanjosephwilliams** [comment]
Interesting. I will try and get some feedback from people on other devices.
I don't think you are misunderstanding...

On Tue, Apr 22, 2014 at 9:20 AM, Rob Brackett notifications@github.comwrote:

> Hmmm, I'm not experiencing that at all on the version you just shipped
> (which I think includes the patch). Unless I'm misunderstanding what you're
> saying :\
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/issues/52#issuecomment-41060879
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
This seems to be resolved. Closing for now.
