### ISSUE TITLE
Connect to default map app when address is tapped

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#55]
In pure-web version of To The Trails, when users tap on the address for a Trailhead, they are routed to their default map application. At that point, To The Trails provides the app with the user's current location and the trailhead address, and offers a route. 

We are aiming for feature parity, and the address (which we currently solicit in the data spec and feature prominently on views across the app) currently don't provide the user much value.

**Comment by lovehandle** [comment]
We're currently unable to detect what the default mapping application is, but we're defaulting to apple maps with directions enabled.

https://github.com/codeforamerica/trails-mobile/commit/7cd7f1d2b771998e371add46a3f15360601c5c6e
