### ISSUE TITLE
Change Maptile UI to simple tap-to-toggle interaction for now

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#57]
While we may have a map-tile package download in the future, we don't have a need for a menu to select from currently. Let's reduce the map tile interaction in the bottom row UI to a simple toggle, with no menu that needs to be opened or closed.

**Comment by lovehandle** [comment]
Closed: https://github.com/codeforamerica/trails-mobile/commit/0795c65f5d386e3e736523370fb70de474229c1c
