### ISSUE TITLE
Hitting the outer bound of map zoom is painful

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#58]
I think it is probably particularly painful because of the canvas approach.

@rclosner what is the file size of adding another z-index or two on the outer-zoom side? We may want to consider including tiles at a zoom level that allows the user to see all trailhead markers within the frame.

**Comment by Mr0grog** [comment]
FWIW, Leaflet's `TileLayer` has a `maxNativeZoom` option (http://leafletjs.com/reference.html#tilelayer-maxnativezoom) that'll just use scaled tiles from a lower zoom level instead of loading actual new tiles, so that might let you do this without bundling more tiles into the app.

**Comment by lovehandle** [comment]
On the outer zoom side, the difference is (relatively) negligible (~ 5-10 MB more?). How many more are you thinking about adding?

**Comment by alanjosephwilliams** [comment]
I think one or two zoom levels would be sufficient. The goal is to provide
a zoom level that enables the user to see the entire universe of
trailheads. This presents a design challenge if the map borders fall within
the viewport, but let's cross the bridge when we arrive.

On Sat, Apr 26, 2014 at 6:06 PM, Ryan Closner notifications@github.comwrote:

> On the outer zoom side, the difference is (relatively) negligible (~ 5-10
> MB more?). How many more are you thinking about adding?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/issues/58#issuecomment-41485492
> .

## 

t:  @alanjosephwilli
p: 817 713 6264
