### ISSUE TITLE
Deselect Trail when Trail Preview is closed

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#60]
Currently, when the user closes the trail preview, the trailhead marker and trail rendered on the map stay selected. 

At the same time, if the user simply taps the map anywhere other than the trailhead, the trailhead-trail pair is deselected.

This creates an awkward and slightly confusing interaction pattern.

Let's deselect the trial-trailhead when the user closes the trail preview, making it consistent with tapping the map.

![2014-04-20 22 28 46](https://cloud.githubusercontent.com/assets/2983464/2756342/85fe6db2-c975-11e3-8836-fbfa4853c282.png)
![2014-04-20 22 28 48](https://cloud.githubusercontent.com/assets/2983464/2756343/860072d8-c975-11e3-8a78-c3f3e6a2e8e3.png)

**Comment by lovehandle** [comment]
Closed: https://github.com/codeforamerica/trails-mobile/commit/e4f14210d2e39dfe265d6f1da648dc6bf1b284ad
