### ISSUE TITLE
Retina Icon and Splash Screen for App Store Submittal

### ISSUE THREAD

**Issue by lovehandle** [opentraildata/OpenTrails-Mobile#70]
On May 1st, Apple will not accept applications that do not support retina display for both icon and splash screen.

http://phonegap.com/blog/build/new-apple-app-store-submittal-rules/

**Comment by alanjosephwilliams** [comment]
Thanks for documenting. I'm on this tomorrow.

On Sat, Apr 26, 2014 at 5:39 PM, Ryan Closner notifications@github.comwrote:

> On May 1st, Apple will not accept applications that do not support retina
> display for both icon and splash screen.
> 
> http://phonegap.com/blog/build/new-apple-app-store-submittal-rules/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/issues/70
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by jmoe** [comment]
This was done in the run-up to summit.
