### ISSUE TITLE
Remove duplicate current location prompt

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#73]
Currently (at least through TestFlight), we are getting two prompts.

The first says the application "To The Trails" would like to use your current location.

The second, duplicate message says:

"/var/mobile/Applications/978ECFE8....../ToTheTrails.app/www/index.html" Would Like to Use Your Current Location.

**Comment by jmoe** [comment]
This has been resolved.
