### ISSUE TITLE
Trigger search when keyboard closes and characters present

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#78]
Currently, the iOS keyboard provides both a "done" and a "search" button when activated by tapping on the search field. 

If the user taps "done", no search is performed. 

Let's perform a search anytime the keyboard is closed, and there are characters present in the search form.

**Comment by lovehandle** [comment]
This will be addressed in the refactor to the controllers file (breaking apart controllers into separate modules).

**Comment by alanjosephwilliams** [comment]
@rclosner can this issue be closed?
