### ISSUE TITLE
Reduce size of trailhead markers when a trail/trailhead is active

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#79]
We have 30px by 30px trailhead markers as default. This size is important for usability.

However, they often get in the way of parsing the map. Particularly when the map zooms out to view a longer trail.

Let's change the size of the markers we render when a trail is selected---when the user is trying to view and parse a particular geometry, let's reduce the clutter on the map.

The simplest approach would probably be creating a 5px by 5px or 10px by 10px marker, and swapping layers when trails are activated and de-activated.

This seems like something @anselmbradford and I could take a pass at this afternoon.

What do you think @rclosner ?

**Comment by alanjosephwilliams** [comment]
We will need to watch out for complications with marker clustering.

**Comment by anselmbradford** [comment]
Addressed in https://github.com/codeforamerica/trails-mobile/pull/104
