### ISSUE TITLE
Make the agency navigation a carousel?

### ISSUE THREAD

**Issue by anselmbradford** [opentraildata/OpenTrails-Mobile#90]
As the app is right now, navigating left and right through the agencies in the notifications view has a start and a finish. I wonder if it would make more sense to make the navigation circular so that while clicking the next arrow >, once the final agency is reached a click of the next arrow just brings the user back to the first one again. 

cc @alanjosephwilliams

**Comment by alanjosephwilliams** [comment]
I agree. I think that a similar navigation pattern should be applied to trails at a trailhead as well. The ordering is not very meaningful (alphabetical), and create a higher friction interaction. Definitely an enhancement for later, though.
