### ISSUE TITLE
Update design for contact view

### ISSUE THREAD

**Issue by anselmbradford** [opentraildata/OpenTrails-Mobile#93]
The address could be styled like the call button on the contacts view. Like it could have an icon followed by the address text. Perhaps something like icon --> http://fortawesome.github.io/Font-Awesome/icon/map-marker/

**Comment by alanjosephwilliams** [comment]
As we discussed earlier, I like that idea. I imagine each button being the full width of the row (+ margins)--you? 

I really like that map marker icon, and I'm investigating font awesome for icons across the app.

**Comment by anselmbradford** [comment]
Yeah that sounds good, though the call button should probably include "Call" then or it'll look a little weird with all the white[blue] space.

**Comment by alanjosephwilliams** [comment]
- Change photo to "embedded on page"
- Style buttons for call and direction
